package uk.gov.justice.digital.hmpps.singleaccommodationserviceapi.query.eligibility.graph

import uk.gov.justice.digital.hmpps.singleaccommodationserviceapi.common.dtos.ServiceResult

/**
 * # Eligibility rules graph
 *
 * --- Example Template
 * Generated by `./gradlew :query:generateEligibilityRulesGraph`. Do not edit by hand.
 *
 * ## Example
 *
 * flowchart TD
 *   RulesetName1["RulesetName1 (1)"]
 *   RulesetName2["RulesetName2 (1)"]
 *   notConfirmed["notConfirmed"]
 *   confirmed["confirmed"]
 *
 *   RulesetName1 -->|PASS| RulesetName2
 *   RulesetName1 -->|FAIL| notConfirmed
 *
 *   RulesetName2 -->|PASS| confirmed
 *   RulesetName2 -->|FAIL| notConfirmed
 *
 * ### Nodes
 *
 * **RulesetName1** (RuleSet)
 * - `RuleA`: Description
 *
 *
 * **RulesetName2** (RuleSet)
 * - `RuleB`: Description
 * - FAIL: `NamedContextUpdater` - Set Upcoming
 *
 * | Outcome | Status | Action | Link | Link type |
 * | --- | --- | --- | --- | --- |
 * | upcoming | Upcoming | START_CAS2_APPLICATION (CAS2) | - | - |
 *
 *
 * **notConfirmed** (Outcome)
 *
 * **confirmed** (Outcome)
 *
 *
 * ## Rule catalogue
 *
 * | Rule | Description | RuleSets | Trees |
 * | --- | --- | --- | --- |
 * | RuleA | Description | RulesetName1 | Diagram Name |
 * | RuleB | Description | RulesetName2 | Diagram Name |
 *
 * ## Context updater catalogue
 *
 * ### NamedContextUpdater
 * Set Upcoming
 * Used by: RulesetName2 (Diagram Name)
 *
 * | Outcome | Status | Action | Link | Link type |
 * | --- | --- | --- | --- | --- |
 * | upcoming | Upcoming | START_CAS2_APPLICATION (CAS2) | - | - |
 * ❯
 * ---
 *
 */
object RulesGraphMarkdownRenderer {

  fun render(graphs: List<RulesGraph>): String = buildString {
    appendLine("# Eligibility rules graph")
    appendLine()
    appendLine("Generated by `./gradlew :query:generateEligibilityRulesGraph`. Do not edit by hand.")
    appendLine()

    graphs.sortedBy { it.treeName }.forEach { graph ->
      appendLine("## ${graph.treeName}")
      appendLine()
      appendLine("```mermaid")
      appendLine("flowchart TD")
      /*
       RulesetName1["RulesetName1"]
       RulesetName2["RulesetName2"]
       notConfirmed["notConfirmed"]
       confirmed["confirmed"]
       */
      graph.nodes.forEach { node ->
        appendLine("  ${node.id}[\"${escape(label(node))}\"]")
      }
      /*
       RulesetName1 -->|PASS| RulesetName2
       RulesetName1 -->|FAIL| notConfirmed
       RulesetName2 -->|PASS| confirmed
       RulesetName2 -->|FAIL| notConfirmed
       */
      graph.edges.forEach { edge ->
        appendLine("  ${edge.from} -->|${edge.label}| ${edge.to}")
      }
      appendLine("```")
      // mermaid drawing closed
      appendLine()

      appendLine("### Nodes")
      appendLine()
      graph.nodes.forEach { node ->
        appendLine(renderNode(node))
        appendLine()
      }
    }

    appendLine("## Rule catalogue")
    appendLine()
    appendLine("| Rule | Description | RuleSets | Trees |")
    appendLine("| --- | --- | --- | --- |")
    catalogueRows(graphs).forEach { row ->
      appendLine("| ${escapeTable(row.className)} | ${escapeTable(row.description)} | ${escapeTable(row.ruleSets)} | ${escapeTable(row.trees)} |")
    }
    appendLine()

    appendLine("## Context updater catalogue")
    appendLine()
    updaterCatalogueRows(graphs).forEach { row ->
      appendLine()
      appendLine(row.description)
      appendLine()
      appendLine("Used by: ${row.usedBy}")
      appendLine()
      if (row.outcomes.isNotEmpty()) {
        append(renderOutcomesTable(row.outcomes))
      }
      appendLine()
    }
  }

  private fun label(node: GraphNode): String = when (node.kind) {
    GraphNodeKind.RULE_SET -> ruleSetLabel(node)
    GraphNodeKind.OUTCOME -> node.title
  }

  private fun ruleSetLabel(node: GraphNode): String {
    val count = node.rules.size
    return if (count == 0) "${node.title} (always PASS)" else "${node.title} ($count)"
  }

  private fun renderNode(node: GraphNode): String = buildString {
    val kind = when (node.kind) {
      GraphNodeKind.RULE_SET -> "RuleSet"
      GraphNodeKind.OUTCOME -> "Outcome"
    }
    append("**${node.title}** ($kind)")
    if (node.kind == GraphNodeKind.RULE_SET) {
      appendLine()
      if (node.rules.isEmpty()) {
        appendLine("- (no rules - always PASS)")
      } else {
        node.rules.forEach { rule ->
          appendLine("- `${rule.className}`: ${rule.description}")
        }
      }
      val updater = node.contextUpdater
      if (updater != null) {
        appendLine("- FAIL: ${failLabel(updater)}")
        if (updater.outcomes.isNotEmpty()) {
          appendLine()
          append(renderOutcomesTable(updater.outcomes))
        }
      }
    }
  }

  private fun failLabel(updater: ContextUpdaterInfo): String = if (updater.name == "constant") {
    updater.description
  } else {
    "`${updater.name}` - ${updater.description}"
  }

  private fun renderOutcomesTable(outcomes: Map<String, ServiceResult>): String {
    val includeBlocking = outcomes.values.any { it.blockingStatusReason != null }
    val headers = buildList {
      add("Outcome")
      add("Status")
      add("Action")
      add("Link")
      add("Link type")
      if (includeBlocking) add("Blocking reason")
    }
    return buildString {
      appendLine("| ${headers.joinToString(" | ")} |")
      appendLine("| ${headers.joinToString(" | ") { "---" }} |")
      outcomes.forEach { (_, result) ->
        val cells = buildList {
          add(escapeTable(result.serviceStatus.name))
          add(escapeTable(result.serviceStatus.name))
          add(escapeTable(actionCell(result)))
          add(escapeTable(result.link ?: "-"))
          add(escapeTable(result.linkType?.name ?: "-"))
          if (includeBlocking) add(escapeTable(result.blockingStatusReason?.name ?: "-"))
        }
        appendLine("| ${cells.joinToString(" | ")} |")
      }
    }
  }

  private fun actionCell(result: ServiceResult): String {
    val action = result.action ?: return "-"
    return "${action.type} (${action.service})"
  }

  private fun escape(value: String): String = value.replace("\"", "#quot;")

  private fun escapeTable(value: String): String = value.replace("|", "\\|")

  private fun updaterCatalogueRows(graphs: List<RulesGraph>): List<UpdaterCatalogueRow> {
    data class Key(val name: String, val description: String, val outcomes: Map<String, ServiceResult>)
    val byUpdater = linkedMapOf<Key, MutableList<UpdaterUse>>()
    graphs.sortedBy { it.treeName }.forEach { graph ->
      graph.nodes.forEach { node ->
        val updater = node.contextUpdater ?: return@forEach
        byUpdater.getOrPut(Key(updater.name, updater.description, updater.outcomes)) { mutableListOf() }
          .add(UpdaterUse(graph.treeName, node.title))
      }
    }
    return byUpdater.map { (key, uses) ->
      UpdaterCatalogueRow(
        name = key.name,
        description = key.description,
        usedBy = uses.map { "${it.ruleSet} (${it.tree})" }.distinct().sorted().joinToString(", "),
        outcomes = key.outcomes,
        anchor = updaterAnchor(ContextUpdaterInfo(key.name, key.description, key.outcomes)),
      )
    }.sortedWith(compareBy({ it.name }, { it.usedBy }))
  }

  private fun catalogueRows(graphs: List<RulesGraph>): List<CatalogueRow> {
    data class Key(val className: String, val description: String)
    val byRule = linkedMapOf<Key, MutableList<Pair<String, String>>>()
    graphs.sortedBy { it.treeName }.forEach { graph ->
      graph.nodes.forEach { node ->
        node.rules.forEach { rule ->
          byRule.getOrPut(Key(rule.className, rule.description)) { mutableListOf() }
            .add(graph.treeName to node.title)
        }
      }
    }
    return byRule.map { (key, uses) ->
      CatalogueRow(
        className = key.className,
        description = key.description,
        ruleSets = uses.map { it.second }.distinct().sorted().joinToString(", "),
        trees = uses.map { it.first }.distinct().sorted().joinToString(", "),
      )
    }.sortedBy { it.className }
  }

  private data class CatalogueRow(
    val className: String,
    val description: String,
    val ruleSets: String,
    val trees: String,
  )

  private data class UpdaterUse(
    val tree: String,
    val ruleSet: String,
  )

  private data class UpdaterCatalogueRow(
    val name: String,
    val description: String,
    val usedBy: String,
    val outcomes: Map<String, ServiceResult>,
    val anchor: String,
  )
}

internal fun updaterAnchor(updater: ContextUpdaterInfo): String {
  val raw = if (updater.name == "constant") {
    val result = updater.outcomes.values.firstOrNull()
    val action = result?.action?.type?.name ?: "no-action"
    val link = result?.link ?: "no-link"
    "${updater.name}-${updater.description}-$action-$link"
  } else {
    updater.name
  }
  return raw.lowercase().replace(Regex("[^a-z0-9]+"), "-").trim('-')
}
