[versions]
hmpps-spring-boot = "3.0.0"
hmpps-sqs = "7.4.0"
springdoc = "3.1.0"
wiremock = "3.13.2"
redisson = "4.7.0"
mockk = "1.14.11"
shedlock = "7.9.0"
swagger-parser = "2.1.46"
hmpps-gradle-spring-boot = "11.0.6"
kotlin = "2.4.10"
apache-commons-csv = "1.14.1"
detekt = "2.0.0-alpha.6"
awaitility = "4.3.0"
javers = "7.11.7"
postgres = "42.7.13"
sentry = "8.51.0"
sar-test-support = "2.8.0"

[plugins]
hmpps-spring-boot = { id = "uk.gov.justice.hmpps.gradle-spring-boot", version.ref = "hmpps-gradle-spring-boot" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
kotlin-jpa = { id = "org.jetbrains.kotlin.plugin.jpa", version.ref = "kotlin" }
detekt = { id = "dev.detekt", version.ref = "detekt" }

[libraries]
hmpps-starter = { module = "uk.gov.justice.service.hmpps:hmpps-kotlin-spring-boot-starter", version.ref = "hmpps-spring-boot" }
hmpps-starter-test = { module = "uk.gov.justice.service.hmpps:hmpps-kotlin-spring-boot-starter-test", version.ref = "hmpps-spring-boot" }
hmpps-sqs = { module = "uk.gov.justice.service.hmpps:hmpps-sqs-spring-boot-starter", version.ref = "hmpps-sqs" }

spring-data-jpa = { module = "org.springframework.boot:spring-boot-starter-data-jpa" }
spring-json = { module = "org.springframework.boot:spring-boot-starter-json" }
jackson-module-kotlin = { module = "tools.jackson.module:jackson-module-kotlin" }
spring-restclient = { module = "org.springframework.boot:spring-boot-restclient" }
spring-flyway = { module = "org.springframework.boot:spring-boot-starter-flyway" }
spring-cache = { module = "org.springframework.boot:spring-boot-starter-cache" }
spring-resttestclient = { module = "org.springframework.boot:spring-boot-resttestclient" }
sentry-spring-boot-starter-jakarta = { module = "io.sentry:sentry-spring-boot-4", version.ref = "sentry" }

# Springdoc
springdoc = { module = "org.springdoc:springdoc-openapi-starter-webmvc-ui", version.ref = "springdoc" }

# Coroutines
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core" }

# Redisson
redisson = { module = "org.redisson:redisson", version.ref = "redisson" }
redisson-spring-cache = { module = "org.redisson:redisson-spring-cache", version.ref = "redisson" }
redisson-boot = { module = "org.redisson:redisson-spring-boot-starter", version.ref = "redisson" }

# Shedlock
shedlock-spring = { module = "net.javacrumbs.shedlock:shedlock-spring", version.ref = "shedlock" }
shedlock-jdbc = { module = "net.javacrumbs.shedlock:shedlock-provider-jdbc-template", version.ref = "shedlock" }

# Testing
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
wiremock = { module = "org.wiremock:wiremock-standalone", version.ref = "wiremock" }
swagger-parser = { module = "io.swagger.parser.v3:swagger-parser", version.ref = "swagger-parser" }
awaitility = { module = "org.awaitility:awaitility-kotlin", version.ref = "awaitility" }
apache-commons-csv = { module = "org.apache.commons:commons-csv", version.ref = "apache-commons-csv" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
sartestsupport = { module = "uk.gov.justice.service.hmpps:hmpps-subject-access-request-test-support", version.ref = "sar-test-support" }
webtestclient = { module = "org.springframework.boot:spring-boot-webtestclient" }

# Runtime
postgres = { module = "org.postgresql:postgresql", version.ref = "postgres" }
flyway-core = { module = "org.flywaydb:flyway-core" }
flyway-postgres = { module = "org.flywaydb:flyway-database-postgresql" }

# Timeline auditing
javers = { module = "org.javers:javers-spring-boot-starter-sql", version.ref = "javers" }